# .streamlit/secrets.toml

# Esta variable detiene la descarga automática de modelos de MediaPipe
# y previene el PermissionError en entornos de sólo lectura (Streamlit Cloud).
MEDIALIBS_DOWNLOAD_AUTO_CHECK = "false"
