# .streamlit/secrets.toml

# La clave de entorno para forzar a MediaPipe a usar modelos locales
# y evitar el PermissionError al descargar en un directorio restringido.
# Nota: Streamlit Cloud lo convierte a la variable de entorno MEDIALIBS_DOWNLOAD_AUTO_CHECK
MEDIALIBS_DOWNLOAD_AUTO_CHECK = "false"
