# .streamlit/secrets.toml

# Esta variable detiene la descarga automática de modelos de MediaPipe
# y previene el PermissionError en entornos de sólo lectura (Streamlit Cloud).
MEDIALIBS_DOWNLOAD_AUTO_CHECK = "false"

# Indica a MediaPipe que use solo archivos locales y no intente descargar,
# evitando el error de permisos.
MEDIAPIPE_ENABLE_DOWNLOADS = "false"
