# .streamlit/secrets.toml

# Usamos una variable para forzar la caché de MediaPipe a un directorio
# donde la aplicación tiene permisos de escritura (el directorio HOME).
# Esto soluciona el PermissionError (Errno 13).

# Establece el directorio de caché de MediaPipe a una ubicación temporal ($HOME)
MEDIAPIPE_DOWNLOAD_DIR = "/tmp/mediapipe_models"
